name: Alias
version: 1.2.3
api: [3.0.0]
author: ZacHack
main: Alias\MainClass

commands:
  alias:
    description: ""
    usage: "/alias <username>"
    permission: "alias.command.alias"

permissions:
  alias:
    default: op
    description: ""
    children:
      alias.command:
        default: op
        description: ""
        children:
          alias.command.alias:
            default: op
            description: ""
